server:
  port: 8010

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springbootwebapp
    username: mathew
    password: mathew
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update